# Директория для загруженных файлов (путь относительно корня)
file.directory=files
# Максимальный размер файла (default 1MB)
spring.servlet.multipart.max-file-size=10MB
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG